# Site Settings
author: Alexandre Mutel
title: SharpDX
description: SharpDX website
baseurl: "/sharpdxWebsite/" # the subpath of your site, e.g. /blog/
url: "http://lebao3105.github.io" # the base hostname & protocol for your site

# Github repository
github_user: lebao3105
github_repo_url: https://github.com/lebao3105/sharpdxWebsite/

# Jekyll settings
permalink: /blog/:year/:month/:day/:title/
# try to fix excerpt separator
excerpt_separator: "" 
# excerpt_link: Read More...
paginate: 10
paginate_path: "/blog/page:num/"

sass:
    style: :compressed

gems:
  - jekyll-sitemap
